# Use uma imagem base do Node.js para o ambiente de desenvolvimento.
FROM node:20-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos package.json e package-lock.json para instalar as dependências.
# O contexto do build será a pasta 'frontend', então não precisamos do prefixo.
COPY package*.json ./

# Instala todas as dependências (incluindo as de desenvolvimento)
RUN npm install

# Copia todo o restante do código da sua aplicação para o diretório de trabalho
COPY . .

# Expõe a porta 5173, que é a porta padrão do Vite
EXPOSE 5173

# Comando para iniciar o servidor de desenvolvimento do Vite
CMD ["npm", "run", "dev"]
