name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend (install, lint, test, build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        # Try a clean CI install first; if lockfile is out-of-sync fall back to npm install
        run: |
          set -e
          npm ci || npm install --no-audit --no-fund

      - name: Lint
        working-directory: ./frontend
        run: npm run lint || true

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --runInBand

      - name: Build
        working-directory: ./frontend
        run: npm run build
